# Generated by Django 4.2.11 on 2024-03-23 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterpriseuser',
            name='Enterprise_Intro',
            field=models.TextField(default=None, max_length=2000),
        ),
        migrations.AddField(
            model_name='enterpriseuser',
            name='Enterprise_Legalperson',
            field=models.TextField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='enterpriseuser',
            name='Enterprise_Name',
            field=models.TextField(default=None, max_length=200),
        ),
    ]
