# Generated by Django 4.2.11 on 2024-03-24 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_enterpriseuser_enterprise_intro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scope1emissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rawcoal_t', models.FloatField(default=0)),
                ('cleanedcoal_t', models.FloatField(default=0)),
                ('coke_t', models.FloatField(default=0)),
                ('naturalgas_104m3', models.FloatField(default=0)),
                ('gasoline_t', models.FloatField(default=0)),
                ('diesel_t', models.FloatField(default=0)),
                ('others_t', models.FloatField(default=0)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('uploadtime', models.DateTimeField(auto_now=True)),
                ('emission', models.FloatField(default=0)),
                ('Enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
