# Generated by Django 4.2.11 on 2024-03-24 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_scope1emissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scope1emissions',
            name='Enterprise',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
