# Generated by Django 4.2.11 on 2024-03-24 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_scope1emissions_enterprise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scope1emissions',
            name='Enterprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scope1', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.CreateModel(
            name='Scope2emissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electricity_104kwh', models.FloatField(default=0)),
                ('heating_GJ', models.FloatField(default=0)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('uploadtime', models.DateTimeField(auto_now=True)),
                ('emission', models.FloatField(default=0)),
                ('Enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scope2', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
