# Generated by Django 4.2.11 on 2024-03-24 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_scope1emissions_enterprise_scope2emissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scope3emissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plane_kyuan', models.FloatField(default=0)),
                ('CRH_kyuan', models.FloatField(default=0)),
                ('train_kyuan', models.FloatField(default=0)),
                ('urbantransport_kyuan', models.FloatField(default=0)),
                ('selfdriving_per', models.FloatField(default=0)),
                ('publictransport_per', models.FloatField(default=0)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('uploadtime', models.DateTimeField(auto_now=True)),
                ('emission', models.FloatField(default=0)),
                ('Enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scope3', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
