# Generated by Django 4.2.11 on 2024-03-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_scope3emissions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scope1emissions',
            old_name='emission',
            new_name='emission1',
        ),
        migrations.RemoveField(
            model_name='scope2emissions',
            name='emission',
        ),
        migrations.RemoveField(
            model_name='scope3emissions',
            name='emission',
        ),
        migrations.AddField(
            model_name='scope1emissions',
            name='fixburn',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='scope1emissions',
            name='movingburn',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='scope2emissions',
            name='electricity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='scope2emissions',
            name='emission2',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='scope2emissions',
            name='heating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='scope3emissions',
            name='commuting',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='scope3emissions',
            name='emission3',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='scope3emissions',
            name='travel',
            field=models.FloatField(default=0),
        ),
    ]
