# Generated by Django 4.2.11 on 2024-03-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_rename_emission_scope1emissions_emission1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterpriseuser',
            name='Enterprise_Intro',
            field=models.TextField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='enterpriseuser',
            name='Enterprise_Legalperson',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='enterpriseuser',
            name='Enterprise_Name',
            field=models.TextField(default='', max_length=200),
        ),
    ]
