# Generated by Django 4.2.11 on 2024-03-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_enterpriseuser_enterprise_intro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scope1emissions',
            name='file1',
            field=models.FileField(default='Nofile.txt', upload_to='./files/'),
        ),
    ]
