# Generated by Django 4.2.11 on 2024-03-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_scope1emissions_file1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scope1emissions',
            name='file1',
            field=models.FileField(default='nofile', upload_to='./files/'),
        ),
    ]
