# Generated by Django 4.2.11 on 2024-03-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_scope1emissions_file1'),
    ]

    operations = [
        migrations.AddField(
            model_name='scope2emissions',
            name='file2',
            field=models.FileField(default='nofile', upload_to='./files/files2'),
        ),
        migrations.AddField(
            model_name='scope3emissions',
            name='file3',
            field=models.FileField(default='nofile', upload_to='./files/files3'),
        ),
        migrations.AlterField(
            model_name='scope1emissions',
            name='file1',
            field=models.FileField(default='nofile', upload_to='./files/files1'),
        ),
    ]
