# Generated by Django 4.2.11 on 2024-03-26 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_scope2emissions_file2_scope3emissions_file3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='offset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('green_electricity_104kwh', models.FloatField(default=0)),
                ('otheroffset_t', models.FloatField(default=0)),
                ('file4', models.FileField(default='nofile', upload_to='./files/files4')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('uploadtime', models.DateTimeField(auto_now=True)),
                ('offset', models.FloatField(default=0)),
                ('Enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offset', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
