# Generated by Django 4.2.11 on 2024-03-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_offset'),
    ]

    operations = [
        migrations.AddField(
            model_name='offset',
            name='is_certified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scope1emissions',
            name='is_certified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scope2emissions',
            name='is_certified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scope3emissions',
            name='is_certified',
            field=models.BooleanField(default=False),
        ),
    ]
