# Generated by Django 4.2.11 on 2024-03-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_offset_is_certified_scope1emissions_is_certified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterpriseuser',
            name='is_Enterprise',
            field=models.BooleanField(default=True),
        ),
    ]
