# Generated by Django 4.2.11 on 2024-03-30 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_enterpriseuser_is_enterprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='offset',
            name='output_wyuan',
            field=models.FloatField(default=0),
        ),
    ]
